apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: devops-project

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend-container

          image: 013046900819.dkr.ecr.ap-south-1.amazonaws.com/eks-backend:latest

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-service:5432/employees
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000

            initialDelaySeconds: 15
            periodSeconds: 10
