apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops-project
type: Opaque

data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: ZW1wbG95ZWVz
